"""P1 — merged-harness seed routing (run_extended_fuzzing._parse_merged_dispatch
+ selector-tagging of raw project seeds).

Bug: a merged dispatcher harness consumes the last `selector_bytes` of every
input as `switch(sel % n)` and feeds Data[0:Size-selector_bytes] as the body.
A raw .icc seed copied verbatim (a) loses its last body byte(s) and (b) routes
to a pseudo-random sub-driver. Fix: tag each raw seed with every sub-driver's
TAIL selector so the format-matching sub-driver gets a clean-body copy.
"""
import importlib

ext = importlib.import_module("scripts.run_extended_fuzzing")


class _Stub:
    """Minimal object exposing _parse_merged_dispatch with a chosen target."""
    def __init__(self, path):
        self.fuzz_target_path = str(path)


_MERGED_SRC = """// Auto-generated by tools/merge_drivers — DO NOT EDIT.
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *Data, size_t Size) {
    // UNIFORM dispatch: last 1 byte(s) select the sub-driver.
    if (Size < 1) return 0;
    uint32_t sel = 0;
    memcpy(&sel, Data + Size - 1, 1);
    switch (sel % 3) {
        case 0: return LLVMFuzzerTestOneInput_01(Data, Size - 1);
    }
    return 0;
}
"""

_PLAIN_SRC = """extern "C" int LLVMFuzzerTestOneInput(const uint8_t *D, size_t S){return 0;}"""


def test_parse_merged_dispatch_detects_merged(tmp_path):
    f = tmp_path / "99.fuzz_target"
    f.write_text(_MERGED_SRC)
    # call the real method unbound against a minimal stub (avoid full __init__)
    got = ext.ExtendedFuzzer._parse_merged_dispatch(_Stub(f))
    assert got == (1, 3), f"expected (selector_bytes=1, n=3), got {got}"


def test_parse_merged_dispatch_plain_returns_none(tmp_path):
    f = tmp_path / "01.fuzz_target"
    f.write_text(_PLAIN_SRC)
    assert ext.ExtendedFuzzer._parse_merged_dispatch(_Stub(f)) is None


def test_tagged_seed_routes_clean_body_to_each_subdriver():
    """The dispatcher contract: sel = last k bytes, body = Data[:Size-k].
    A seed tagged `body + d.to_bytes(k)` must route to sub-driver d with the
    ORIGINAL body intact (no truncation of real content)."""
    body = b"acsp-ICC-profile-bytes" * 8   # stand-in for a real .icc body
    k, n = 1, 3
    for d in range(n):
        tagged = body + d.to_bytes(k, "little")
        # replicate the C dispatcher
        sel = int.from_bytes(tagged[len(tagged) - k:], "little")
        routed = sel % n
        recovered_body = tagged[: len(tagged) - k]
        assert routed == d, f"seed tagged for {d} routed to {routed}"
        assert recovered_body == body, "body corrupted by tagging"


def test_untagged_seed_corrupts_body_and_misroutes():
    """Document the BUG the fix addresses: a raw seed loses its last byte and
    routes by its trailing content (pseudo-random)."""
    body = b"acsp-ICC-profile-bytes" * 8
    k, n = 1, 3
    sel = int.from_bytes(body[len(body) - k:], "little")
    routed = sel % n
    recovered_body = body[: len(body) - k]
    assert recovered_body != body          # last byte stolen as selector
    # routing is whatever the trailing byte happens to be — not guaranteed 0
    assert routed == sel % n
